### ISSUE TITLE
fazer tela listar entregadores

### ISSUE THREAD

**Issue by laupontiroli** [laupontiroli/front_ifood_arqproj#3]
fazer uma tela que lista todos os entregadores

**Comment by jonasbp** [comment]
@laupontiroli essa que posso adiantar para fazer?

**Comment by laupontiroli** [comment]
Nn consigo ver o git agora to sem computador, mas provavelmente sim

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Jonas Bonfá ***@***.***>
Enviado: Monday, May 6, 2024 10:48:25 PM
Para: laupontiroli/front_ifood_arqproj ***@***.***>
Cc: Laura Pontiroli Machado ***@***.***>; Mention ***@***.***>
Assunto: Re: [laupontiroli/front_ifood_arqproj] fazer tela listar entregadores (Issue #3)


@laupontiroli<https://github.com/laupontiroli> essa que posso adiantar para fazer?

**Comment by juliaas2** [comment]
já fiz

**Comment by juliaas2** [comment]
Lista entregadores feita
